### ISSUE TITLE
User Issue: issue with cgroups in EKS

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#317]
Hi folks 👋

Thanks for open-sourcing this project. Great work.

**Describe the bug**

I am trying to run Disruptions in a EKS cluster and I'm facing issues with the cgroup path.

The error I am seeing when deploying a Disruption is the following:
```
{"level":"fatal","ts":1621863086297.7078,"caller":"injector/main.go:151","message":"can't create container object","disruptionName":"containers-targeting","disruptionNamespace":"chaos","targetName":"echoserver-7bfc76f9bd-pxtl6","error":"error getting cgroup path: unexpected cgroup format: /kubepods/besteffort/podcbd5ece0-ec07-4de2-a37f-54c4fc753f7e","stacktrace":"main.initConfig\n\t/go/src/github.com/DataDog/chaos-controller/cli/injector/main.go:151\ngithub.com/spf13/cobra.(*Command).preRun\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\t/go/src/github.com/DataDog/chaos-controller/cli/injector/main.go:92\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"}
/kubepods/besteffort/podcbd5ece0-ec07-4de2-a37f-54c4fc753f7e
```

**To Reproduce**
These are the steps I followed on my setup.
1) I installed any resources through the `install.yaml` file.
2) I also deployed a `echoserver` app under a different `chaos` namespace.
3) Finally, I deployed the following Disruption:
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: containers-targeting
  namespace: chaos
spec:
  level: pod
  selector:
    app: echoserver
  count: 100%
  network:
    drop: 100
```

**Expected behavior**
The injector pod runs the Disruption without errors.

**Screenshots**
N/A

**Environment:**
 - Kubernetes version: EKS 1.18
 - Controller version: 
 - Cloud provider (or `local`): AWS
 - Base OS for Kubernetes: Amazon Linux 2
 - Container runtime: docker://19.3.6

**Additional context**
Based on the error message, the CGroupParent which is parsed [here](https://github.com/DataDog/chaos-controller/blob/bc1c8f269a9d38216709b461d5b8bccf12ec9e80/container/docker.go#L57) does not meet the format the controller is expecting.

I then tried something like [that](https://gitlab.cncf.ci/kubernetes/kubernetes/blob/42289c27580ab7d7f5b8593600c86c7eb0845b34/pkg/kubelet/cm/cgroup_manager_linux.go#L48) (I am not sure if that makes sense?) but when the Disruption was injected I got the following error message:
```
{"level":"error","ts":1622047742022.986,"caller":"injector/main.go:235","message":"disruption injection failed","disruptionName":"containers-targeting","disruptionNamespace":"chaos","targetName":"echoserver-7bfc76f9bd-qt4bs","error":"error writing classid to pod net_cls cgroup: error opening cgroup file /mnt/cgroup/net_cls/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd8ab9bfd_581f_4191_9b4d_90dab3356e0d.slice/net_cls.classid: open /mnt/cgroup/net_cls/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd8ab9bfd_581f_4191_9b4d_90dab3356e0d.slice/net_cls.classid: no such file or directory","stacktrace":"main.injectAndWait\n\t/Users/nkatirtzis/github/chaos-controller/cli/injector/main.go:235\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/nkatirtzis/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/nkatirtzis/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/nkatirtzis/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\t/Users/nkatirtzis/github/chaos-controller/cli/injector/main.go:92\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```

**Comment by blazebissar** [comment]
I ran into the same issue when trying out a CPU disruption and found a [fix](https://github.com/DataDog/chaos-controller/pull/323) that handles it on my system. I'm still working to confirm that there aren't additional edge cases but if you wanted to try it out it might work for you too.

**Comment by nikos912000** [comment]
Hi @blazebissar.
Awesome, that seems to work. Thanks a lot.

**Comment by Devatoria** [comment]
@nikos912000 we merged the PR and we will release a new patch version soon, thank you for opening the issue!
