### ISSUE TITLE
User Request: Push 4.0.1 images to DockerHub

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#339]
**Is your feature request related to a problem? Please describe.**
Now that the 4.0.1 release is out would it be possible to push the latest images to DockerHub?

**Describe the solution you'd like**
It'd be great if the latest Docker images get pushed to DockerHub on every release. We do something similar with GitHub Actions in our projects ([example](https://github.com/ExpediaGroup/mittens/blob/main/.github/workflows/docker-build-push.yml)).

**Describe alternatives you've considered**
The alternative is to keep pushing the images manually but it adds overhead.

**Comment by Devatoria** [comment]
Sorry, we forgot to trigger the job which is still manual but which we should make automatic very soon. It should be ok now!
