### ISSUE TITLE
Chaos Controller pods in Container Creating State

### ISSUE THREAD

**Issue by Bhumika1997** [DataDog/chaos-controller#369]
Hi,
I have installed Chaos Controller but my Chaos Controller pods are in Container Creating State
![image](https://user-images.githubusercontent.com/33874082/126589307-64f019f6-6f1c-4595-986c-10d9c0e3186d.png)
Can somebody please help me on this?

**Comment by ptnapoleon** [comment]
Hi, can you please share the output of `kubectl describe` on those pods, please?

**Comment by Bhumika1997** [comment]
> Hi, can you please share the output of `kubectl describe` on those pods, please?

![image](https://user-images.githubusercontent.com/33874082/126781348-0411cc40-2019-43cc-8696-351147c77a1b.png)
I am getting error while doing kubectl describe pod

**Comment by ptnapoleon** [comment]
Hmm, that's odd, for the pod to be in `ContainerCreating`, it must exist to be described. Are you still seeing the pod with `kubectl get pods`? Do you need to specify the namespace too when describing, perhaps? If you still can't describe the pod, any luck with describing the deployment?
