### ISSUE TITLE
User Request: Compatibility with Kubernetes 1.22

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#467]
The Kubernetes 1.22 release brought a set of backwards incompatible changes.
One that affects this project is the [removal of deprecated beta APIs](https://kubernetes.io/blog/2021/08/04/kubernetes-1-22-release-announcement/#removal-of-several-deprecated-beta-apis).

**Is your feature request related to a problem? Please describe.**
The provided charts are not compatible with Kubernetes 1.22.

**Describe the solution you'd like**
Update any deprecated APIs. There is a [migration guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122) for this.
Depending on the Kubernetes versions we'd like to support in this project we need to check in which version the stable APIs were introduced.

**Comment by Devatoria** [comment]
Thanks for reaching out. We'll track that internally to be compatible with 1.22.

**Comment by Devatoria** [comment]
Closing this issue very very late. We ran tests against the current codebase of the controller and everything should be working fine up to the latest k8s release (1.26.1).
