### ISSUE TITLE
User Request: Feature flag to disable deletion of Disruption

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#497]
**Is your feature request related to a problem? Please describe.**
Our team is working on integrating the chaos controller with our CI/CD platform.

The setup we have is as follows:
- [Kubefed](https://github.com/kubernetes-sigs/kubefed) acts as the control plane and propagates any changes to worker clusters.
- Worker clusters are the ones where workloads get deployed. These are the clusters where we run Disruptions.
- The Spinnaker pipeline deploys Disruptions to the worker clusters through Kubefed.

Right now the deletion of Disruptions is done by the controller. This is happening once the Disruption expires and after the GC period.
This is great, but with a control plane we tend to have kubefed handling the lifecycle of any resources deployed to worker clusters. Ideally the responsibility to delete Disruptions would be on Spinnaker and Kubefed.

**Describe the solution you'd like**
Introduce a toggle in the controller's ConfigMap which disables the deletion.

**Describe alternatives you've considered**
The other option for us is to set the GC to a very large value so Spinnaker/Kubefed are always the first ones to do the deletion.

**Additional context**
Let us know if you have any other ideas. If this can be solved in a different way happy to consider it!

**Comment by ptnapoleon** [comment]
Absolutely, happy to add this

**Comment by nikos912000** [comment]
Awesome, thank you.
Is it just checking this flag in [here](https://github.com/DataDog/chaos-controller/blob/fbb4fad2952ab3390ebe4188e071b27b926663cc/controllers/disruption_controller.go#L174)?
Happy to raise the PR.

**Comment by ptnapoleon** [comment]
Yes, more or less. I will have a PR for you to review today
