### ISSUE TITLE
User Request: Support for percentage in CPU stress

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#507]
**Is your feature request related to a problem? Please describe.**
A common use case for CPU stress is for testing CPU-based autoscaling. Right now the controller only supports 100% of CPU pressure.
It would be great to be able to specify percentages.

**Describe the solution you'd like**
Looking at the implementation, the injector Pod creates a goroutine per core. I'm wondering if the lack of support for percentage-based stress is due to that.

**Describe alternatives you've considered**
N/A

**Comment by nikos912000** [comment]
Thanks Joris.

Got it, it gets tricky due to its implementation.

I think a percentage would be more user-friendly, but if it is not deterministic it may confuse the users.

Do you know how tools like [stress-ng](http://manpages.ubuntu.com/manpages/bionic/man1/stress-ng.1.html) achieve the that? It seems to support number of workers (cores) and load (percentage).

**Comment by Devatoria** [comment]
Hi Nikos, sorry for the late reply, we didn't link this issue in the related PR but the feature is now available (for a few versions actually).
