### ISSUE TITLE
User Request: Debugging instructions

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#510]
**Is your feature request related to a problem? Please describe.**
It would be nice to provide instructions on how to debug the controller vs an existing cluster.
Running this locally, in an IDE, requires some effort but is feasible.

**Describe the solution you'd like**
Any required files and documentation on how to run the controller -in an IDE- vs an existing cluster.

**Describe alternatives you've considered**
Deploying the controller to a cluster and relying on logs/metrics.

**Additional context**
Quick overview of running it locally:
- Generate the webhook certificates; one can get these from the cluster as long as the controller has been installed there before. Or we can provide dummy ones?
- Create the `config.yaml` file
  - This is similar to the one provided as a ConfigMap
  - Leader election and safeguards should be disabled
  - Provide the directory with the certificates
- Set the `--config` argument, and the `CONTROLLER_NODE_NAME` environment variable when running the controller.

Would it help if we introduce a `local` folder with a sample `config.yaml` and dummy certificates?

**Comment by ptnapoleon** [comment]
I don't ever run the controller in an IDE, though I do know ` requires some effort but is feasible.` to be true. Is this something you have working?

**Comment by nikos912000** [comment]
> I don't ever run the controller in an IDE, though I do know ` requires some effort but is feasible.` to be true. Is this something you have working?

Hey Philip. Yes, I got a working setup so happy to document it.

**Comment by Devatoria** [comment]
#515 is merged, I'm closing this one, thanks!
