### ISSUE TITLE
User Issue: Status not being a subresource causes issues with control planes

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#511]
**Describe the bug**
Right now, the status is not defined as a [subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#status-subresource) in the CRD. This means that the entire object gets updated, including its generation.

This causes issues, especially when integrating with control planes, like Kubefed; the control plane sees the object's generation getting updated and reconciles, causing an infinite loop.

I was curious if there was a particular reason behind the implementation. Is it possible to change this?

**To Reproduce**
The issue is more obvious when having a control plane.

**Expected behavior**
The status is defined as a subresource in the CRD. This would allow updating just the status rather than the entire object.

**Additional information**
Subresources in Kubebuilder: https://book.kubebuilder.io/reference/generating-crd.html?highlight=subresourc#subresources

**Comment by ptnapoleon** [comment]
>  there was a particular reason behind the implementation

Not especially, it was just extra work at the time, and we didn't have a need for it. I think we're willing to change it

**Comment by nikos912000** [comment]
That would be very useful. We are integrating with Kubefed and Spinnaker and this unfortunately causes a lot of issues :(

I hope it makes sense from a design point of view - this is how most controllers define the status afaik.

From a quick look, the following changes are needed:
- [This](https://github.com/DataDog/chaos-controller/blob/a16e95d9f238d5eed6cee2c07430ecdb3d8e1c90/controllers/disruption_controller.go#L313) is the only place where the controller itself updates the status.
- The webhooks patch the object, so these calls need to be updated.
- And then the CRD plus the addition of the [kubebuilder annotation](https://book.kubebuilder.io/reference/generating-crd.html?highlight=subresourc#status).

PS: Thanks for being super fast with any issues!

**Comment by ptnapoleon** [comment]
Closed by https://github.com/DataDog/chaos-controller/pull/520 , hopefully? We will cut a release this week

**Comment by nikos912000** [comment]
Amazing, thank you @ptnapoleon!
