### ISSUE TITLE
User Issue: Traffic surge once a packet drop network failure finishes

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#526]
**Describe the bug**
We have been testing the packet drop failures internally. One thing we noticed is that once an experiment finishes there is significant traffic surge in the targeted applications which can harm them.

I may be missing implementation details but aren't packets dropped completely instead of piling up?

**To Reproduce**
In minikube:
1. Deploy the following Disruption:
```
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: network-egress-drop
  namespace: chaos-demo
spec:
  level: pod
  selector:
    app: "demo-curl"
  count: 100%
  containers:
    - "curl"
  duration: 3m0s
  network:
    drop: 100
    hosts:
      - host: demo.chaos-demo.svc.cluster.local
```
2. During the experiment, we can see the connection failures:
```
Failed to connect to demo.chaos-demo.svc.cluster.local port 8080 after 31757 ms: Operation timed out
```
3. Once the experiment finishes all these requests/responses show up within a short time-window:
```
2022-03-21T16:31:34.033598753Z 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.107.44.112:8080...
2022-03-21T16:31:49.405143841Z 
...
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0* Connected to demo.chaos-demo.svc.cluster.local (10.107.44.112) port 8080 (#0)
2022-03-21T16:31:49.405213092Z > GET / HTTP/1.1
2022-03-21T16:31:49.405227382Z > Host: demo.chaos-demo.svc.cluster.local:8080
...
2022-03-21T16:31:55.472746326Z * Connected to demo.chaos-demo.svc.cluster.local (10.107.44.112) port 8080 (#0)
2022-03-21T16:31:55.472960280Z > GET / HTTP/1.1
2022-03-21T16:31:55.472984764Z > Host: demo.chaos-demo.svc.cluster.local:8080
...
```

**Expected behavior**
No traffic surge as packets/requests should be dropped rather than piling up.

**Screenshots**
This is from our internal test cluster:
<img width="1007" alt="Screenshot 2022-03-18 at 19 15 11" src="https://user-images.githubusercontent.com/6031527/159325756-80ef6342-b63a-4d35-a1c6-2baf7af33552.png">

**Environment:**
- Kubernetes version: 1.20.11
- Controller version: 6.0.0
- Cloud provider (or local): EKS
- Base OS for Kubernetes: Amazon Linux 2
- Container runtime: containerd

**Comment by ptnapoleon** [comment]
Hmm, we're just telling `tc` to drop the packets, and afaict from reading tc documentation, they should literally be dropped

**Comment by nikos912000** [comment]
Thanks for the context 👍 

Adding a few more details below.

> If, in your application, you have some retry mechanism creating a new routine/thread/process for a new request on failure, you may start piling up requests.

Indeed, we had this in mind. We are testing using a -synchronous- client that does not implement retries. But the Istio proxy sidecar which is running alongside the application's container may retry requests.

> We do not seem to observe this with our curl demo pod which creates one process at a time?

Based on the above, I tried replicating the issue in minikube. I've included the reproduction steps. If I am not missing anything, in step 3 we should not see these requests/responses once the experiment finishes?
As based on the [docs](https://curl.se/docs/manpage.html) `curl` does not retry by default.

**Comment by Devatoria** [comment]
> Based on the above, I tried replicating the issue in minikube. I've included the reproduction steps. If I am not missing anything, in step 3 we should not see these requests/responses once the experiment finishes?
As based on the [docs](https://curl.se/docs/manpage.html) curl does not retry by default.

Can you see the surge of requests incoming in the demo-nginx pod logs on disruption removal? Just to confirm that what you're observing through metrics is actually what's really happening please (ie. a lot of "stuck" requests reaching the nginx pod suddenly on disruption removal).

**Comment by nikos912000** [comment]
Sorry, I had a different mental model for the demo-curl...
This sends a request every second by default (e.g. in minikube) but in our clusters we override that to be every 30s.

I tested again in minikube and the requests I am seeing on the client and Nginx side are the ones initiated after the experiment finishes.

We will check our application's client and Istio as they may be the reason. Thanks for the help!

**Comment by Devatoria** [comment]
👍  You're welcome. I'm closing the issue for now but feel free to re-open it if there's anything else showing up about this.
