### ISSUE TITLE
User Issue: CPU pressure does not consume 100% of the pods allocated CPU

### ISSUE THREAD

**Issue by sasidharsmit** [DataDog/chaos-controller#538]
**Describe the bug**
"CPU pressure" attack does not consume 100% of the CPU allocated to a Kubernetes pod.

**To Reproduce**
I injected a "CPU pressure" fault into a pod with 2 containers:

1. Application container (name: fault-injection-showcase, CPU requests: 16 cores, CPU limits: 16 cores)
2. Istio sidecar container (name: istio-proxy, CPU requests: 100 millicores, CPU limits: 2 cores)

**Expected behavior**
The pod should consume 18 cores (100% of the CPU allocated to both the containers in the pod)

**Actual behavior**
1. The pod CPU usage fluctuates anywhere between 7 to 18 cores
2. Within the pod, the "istio-proxy" container was constantly at 100% CPU usage but the "fault-injection-showcase" container was only using ~60% all the time

**Screenshots**
<img width="1613" alt="CPU_Usage_Over_Time" src="https://user-images.githubusercontent.com/19797644/168576470-b7edc740-39a5-449b-8a91-c7c17cfd7e41.png">

<img width="1239" alt="CPU_Usage_Containers_In_The_Pod" src="https://user-images.githubusercontent.com/19797644/168576517-5c8a82e8-6a13-4212-92ca-16b18e61c450.png">

<img width="1249" alt="CPU_Usage_Application_Container" src="https://user-images.githubusercontent.com/19797644/168576535-a03bd281-775a-49fc-a1b2-7122b7fda6e6.png">

<img width="1243" alt="CPU_Usage_Istio_Proxy_Container" src="https://user-images.githubusercontent.com/19797644/168576557-f9f709b2-40aa-432b-8e30-22bbdfae0bfe.png">

**Environment:**
 - Kubernetes version: v1.21.9
 - Controller version: 6.0.0
 - Cloud provider (or `local`): AWS
 - Base OS for Kubernetes: Amazon Linux (5.4.181-99.354.amzn2.x86_64)

**Comment by Devatoria** [comment]
Hey, sorry for the late answer, we shipped a fix for that a while ago but didn't mention it here. Let us know if it's still a problem and we'll re-open.
