### ISSUE TITLE
User Issue / Suggestion: Controller arguments do not supersede config file

### ISSUE THREAD

**Issue by craig-seeman** [DataDog/chaos-controller#707]
**Describe the bug**
Small bug found: When using a configuration file along with command arguments, the arguments used are overridden by contents of the config file which caused a bit of confusion on our end during setup.

**To Reproduce**
1. Set a value within the configmap/config file (ex: notifiers-common-clustername)
2. Add an argument while launching the binary (ex: notifiers-common-clustername)

**Expected behavior**
When setting a command line argument, the value provided will take precedence over the same setting in the configuration file.

**Environment:**
 - Kubernetes version: N/A
 - Controller version: N/A
 - Cloud provider (or `local`): N/A
 - Base OS for Kubernetes: N/A

**Additional context**
Looks like a potential fix would be to call the codeblock containing `viper.SetConfigFile(configPath)` directly after only loading the `configPath` pvar and calling a pflag.Parse() and then continue on withe the rest of the flags.

**Comment by ptnapoleon** [comment]
> When setting a command line argument, the value provided will take precedence over the same setting in the configuration file.

I'm not sure we share this expectation? @Devatoria, what do you think?

**Comment by luphaz** [comment]
I will create a new release `7.21.0` to make [this](https://github.com/DataDog/chaos-controller/commit/3e1ecd8228e7ca607f94004f96dd5ce340234b7d) available
