### ISSUE TITLE
User Request: Add support for tolerations on injector pods

### ISSUE THREAD

**Issue by craig-seeman** [DataDog/chaos-controller#814]
**Is your feature request related to a problem? Please describe.**
Currently the injector pods created do not support having tolerations added to them, making it hard/impossible to have injector pods spawned on certain node setups that have taints applied to them.

**Describe the solution you'd like**
Add the ability for tolerations to be added to the injector pods, defined within values.yaml, much like annotations and labels.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by ptnapoleon** [comment]
Thanks @JoshuaBell9181 for adding this feature
