### ISSUE TITLE
User Issue: OnInit Chaos handler loop

### ISSUE THREAD

**Issue by expFlower** [DataDog/chaos-controller#822]
**Describe the bug**
When validating the oninit feature within our environment we see that the following scenario can happen:
The chaos handler container is successfully attached to the pod spec, the handler runs as expected however if a SIGUSER1 signal is not received within the timeout set the chaos-handler exits unsuccessfully (exit code 1)

Looking at the documentation: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior, this means that if your pod has either a restart policy of `always` or `onFailure` the pod will never successfully start unless a disruption is injected and the handler receives the SIGUSER1 signal.

**To Reproduce**
1. Pod restart policy is set to `Always` for a deployment
2. The deployment pod contains the label `chaos.datadoghq.com/disrupt-on-init`
3. onInit is enabled within the controller
4. A disruption is not created prior to the timeout set.

**Expected behavior**
If the timeout value has exceeded and a disruption is not created then the pod should start up as normal.

**Screenshots**

**Environment:**
 - Kubernetes version: v1.25.16
 - Controller version: 8.4.1
 - Cloud provider (or `local`): aws
 - Base OS for Kubernetes: amazon linux

**Additional context**
Suggested fix would to change the exit code here:
https://github.com/DataDog/chaos-controller/blob/b395eb7b9066423c8b34066e32d7dc35eb614cc3/cli/handler/main.go#L41-L43

**Comment by ptnapoleon** [comment]
I'll note that we implemented this behavior on purpose, as we wanted to strongly disincentivize the label `chaos.datadoghq.com/disrupt-on-init` being used outside of human created/monitored disruptions.

However, I can see why you'd want it to behave differently. At the very least, it should be okay for that exit code to be configurable

**Comment by expFlower** [comment]
Hi @ptnapoleon thanks for the response and i can certain see why this design decision was made. I think i've found a process internally to leverage this feature with it's current design. It'll take me a little bit of time to validate as i need to update our CICD product to handle this. 

If not and we still need to have the init container exit successfully i'll cut a draft PR to be able to pass a flag to configure this behaviour as suggested.

Thanks
David
