### ISSUE TITLE
User Request: Dashboard in Datadog

### ISSUE THREAD

**Issue by xpdable** [DataDog/chaos-controller#850]
Does someone have practice to create dashboard according to chaos.* metrics with application metrics in datadog dashboard?
So that SRE can easily monitoring/compare the chaos injection with steady states?
Thanks in advacne.

**Comment by ptnapoleon** [comment]
Hi. Yes, we can probably share the queries we're using for specific widgets. Is there anything in particular you'd like to visualize that you're having trouble with?

**Comment by xpdable** [comment]
> Hi. Yes, we can probably share the queries we're using for specific widgets. Is there anything in particular you'd like to visualize that you're having trouble with?

Hi Philip, my idea is quite simple now for pilot showcase.
0) I make a widget showing the application status, saying the http response code distribution either 2xx or >4xx, in bar chart over timeseries.
1) I want to make another widget where metrics from chaos controller over timeseries that show when my DisruptionCron/Disruption are injected.
Then I put these two in one dashboard, so it would be a clear view of steady state vs. turbulence.

**Comment by xpdable** [comment]
@ptnapoleon Do you have some good idea of it? Thanks
